### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by ninthDevilHAUNSTER** [anbai-inc/javaweb-sec#8]
https://javasec.org/javase/Reflection/Reflection.html#%E5%8F%8D%E5%B0%84%E8%B0%83%E7%94%A8%E6%88%90%E5%91%98%E5%8F%98%E9%87%8F

在该文章中有7处将class写成了 clazz

**Comment by ver007** [comment]
自JDK 1.0起，`clazz` 已用于Java代替保留字"class"，"class"是你想要的，但缩写或插入垃圾("a"，"the"，"_"等)会降低清晰度，'class'是一个保留关键字，因此不允许使用Class class。所以，你会看到Class clazz或Class cls。
